import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { test } from "node:test"

const root = resolve(import.meta.dirname, "..")
const read = (path) => readFileSync(resolve(root, path), "utf8")

test("data source management does not show configuration completion", () => {
  const view = read("src/views/DataSourceSettings.vue")

  assert.doesNotMatch(view, /配置完成度/)
  assert.doesNotMatch(view, /datasourceCompletion/)
  assert.match(view, /label="表结构"/)
  assert.match(view, /schemaTablesCount\(row\)/)
  assert.match(view, /row\.drill_config \? '已配置钻取' : '未配置钻取'/)
})

test("data source recommendation questions can be generated by llm", () => {
  const view = read("src/views/DataSourceSettings.vue")

  assert.match(view, /generate-recommend-questions/)
  assert.match(view, /generateRecommendQuestions/)
  assert.match(view, /generatingRecommendQuestions/)
  assert.match(view, /AI 生成/)
})

test("new data sources auto detect schema on create", () => {
  const view = read("src/views/DataSourceSettings.vue")

  assert.match(view, /已自动检测表结构/)
  assert.match(view, /推荐问题将在后台生成/)
  assert.doesNotMatch(view, /已自动检测表结构并生成/)
  assert.doesNotMatch(view, /请点击「表结构」按钮配置表结构/)
})

test("data source editor does not expose dataset metric descriptions", () => {
  const view = read("src/views/DataSourceSettings.vue")

  assert.doesNotMatch(view, /指标描述/)
  assert.doesNotMatch(view, /未维护指标描述/)
  assert.doesNotMatch(view, /metrics_prompt/)
  assert.match(view, /推荐问题/)
})
