import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { test } from "node:test"

const root = resolve(import.meta.dirname, "..")
const read = (path) => readFileSync(resolve(root, path), "utf8")

test("smart query exposes only business and agentic modes", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")
  const authStore = read("src/store/auth.ts")

  assert.match(view, /业务问数/)
  assert.match(view, /探索模式/)
  assert.match(view, /canUseAgenticMode/)
  assert.match(view, /label="agentic"/)
  assert.match(view, /useAuthStore/)
  assert.match(authStore, /canUseAgenticMode/)
  assert.match(authStore, /dept_admin/)
  assert.match(store, /QueryMode = "business" \| "agentic"/)
  assert.match(store, /mode: "business" as QueryMode/)
  assert.doesNotMatch(view, /闲聊模式/)
  assert.doesNotMatch(view, /Agentic 问数/)
  assert.doesNotMatch(view, /label="explore"/)
  assert.doesNotMatch(view, /label="chat"/)
  assert.doesNotMatch(store, /"chat"/)
})

test("business query defaults to dataset scope and keeps SQL in result details", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(store, /scopeMode: "dataset" as QueryScopeMode/)
  assert.match(view, /queryStore\.mode === "business"/)
  assert.match(view, /业务问数必须选择数据集/)
  assert.doesNotMatch(view, /默认使用可信指标和数据集语义层/)
  assert.match(bubble, /openResultDetail\('sql'\)/)
  assert.match(bubble, /result-detail-sql/)
  assert.doesNotMatch(bubble, /技术细节 \/ SQL 查询语句/)
  assert.doesNotMatch(bubble, /class="sql-collapse"/)
  assert.doesNotMatch(bubble, /探索结果，非认证口径/)
  assert.doesNotMatch(bubble, /message\.mode === ['"]explore['"]/)
})

test("query history provides searchable CRUD controls and a new conversation entry", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(view, /新建对话/)
  assert.match(view, /startNewConversation/)
  assert.match(view, /queryStore\.clearMessages\(\)/)
  assert.match(view, /historyLoadingId/)
  assert.match(view, /isRestoringHistory/)
  assert.match(view, /history-loading-icon/)
  assert.match(view, /if \(historyLoadingId\.value \|\| queryStore\.loading\) return/)
  assert.match(view, /try[\s\S]+queryStore\.loadHistoryDetail\(item\.id\)[\s\S]+finally[\s\S]+historyLoadingId\.value = null/)
  assert.match(view, /refreshHistoryForScope/)
  assert.match(view, /if \(isRestoringHistory\.value\) return/)
  assert.match(view, /historySearch/)
  assert.match(view, /historyFilter/)
  assert.match(view, /filteredHistory/)
  assert.match(view, /historyEmptyDescription/)
  assert.match(view, /confirmDeleteHistoryItem/)
  assert.match(view, /ElMessageBox\.confirm/)
  assert.match(view, /history-empty-actions/)
  assert.match(view, /收藏/)
  assert.match(view, /清空历史/)
  assert.match(view, /formatHistoryDate/)
  assert.match(store, /currentConversationRootHistoryId/)
  assert.match(store, /currentConversationContextKey/)
  assert.match(store, /buildConversationContextKey/)
  assert.match(store, /const canContinueConversation = this\.currentConversationContextKey === conversationContextKey/)
  assert.match(store, /const effectiveParentHistoryId = parentHistoryId \?\? \(canContinueConversation \? this\.currentConversationRootHistoryId : null\)/)
  assert.match(store, /parent_history_id: effectiveParentHistoryId \|\| null/)
  assert.match(store, /this\.currentConversationContextKey = conversationContextKey/)
  assert.match(store, /conversationRootId/)
  assert.match(store, /conversationDatasourceId/)
  assert.match(store, /datasource_id/)
  assert.match(store, /data\.conversation/)
  assert.match(store, /fromHistory\?: boolean/)
  assert.match(store, /fromHistory: true/)
})

test("smart query workspace uses modern guided interactions", () => {
  const view = read("src/views/SmartQuery.vue")

  assert.match(view, /query-workspace/)
  assert.match(view, /query-compact-workspace/)
  assert.match(view, /query-workbench-toolbar/)
  assert.match(view, /query-mode-switcher/)
  assert.match(view, /query-toolbar-actions/)
  assert.match(view, /query-toolbar-scope/)
  assert.match(view, /query-mode-switcher[\s\S]+query-toolbar-scope[\s\S]+query-toolbar-actions/)
  assert.match(view, /class="mode-tabs query-mode-switcher"/)
  assert.match(view, /query-history-left-layout/)
  assert.match(view, /grid-template-areas: "history chat"/)
  assert.match(view, /\.conversation-shell\s*{[\s\S]*grid-area: chat/)
  assert.match(view, /\.query-side-panel\s*{[\s\S]*grid-area: history/)
  assert.match(view, /welcome-panel/)
  assert.match(view, /query-start-panel/)
  assert.match(view, /welcome-primary/)
  assert.match(view, /query-start-copy/)
  assert.match(view, /prompt-suggestion-rail/)
  assert.match(view, /query-prompt-list/)
  assert.match(view, /query-prompt-action/)
  assert.match(view, /--query-primary: #0f766e/)
  assert.match(view, /\.smart-query-page :deep\(\.el-button\)/)
  assert.match(view, /\.smart-query-page :deep\(\.el-tag\)/)
  assert.match(view, /\.scope-select :deep\(\.el-select__wrapper\)/)
  assert.match(view, /\.history-filter[\s\S]+var\(--query-primary\)/)
  assert.match(view, /\.history-filter :deep\(\.el-segmented__item\.is-selected\)[\s\S]+color: #ffffff/)
  assert.match(view, /\.history-filter :deep\(\.el-segmented__item\.is-selected \.el-segmented__item-label\)[\s\S]+color: #ffffff/)
  assert.match(view, /popper-class="query-scope-popper"/)
  assert.match(view, /:global\(\.query-scope-popper\)/)
  assert.match(view, /\.welcome-message\s*{[\s\S]*width: min\(100%, 760px\)[\s\S]*grid-template-columns: 1fr/)
  assert.doesNotMatch(view, /grid-template-columns: minmax\(220px, 0\.72fr\) minmax\(340px, 1\.28fr\)/)
  assert.match(view, /\.welcome-primary\s*{[\s\S]*background: var\(--query-surface\)/)
  assert.match(view, /\.prompt-suggestion-card \.el-icon\s*{[\s\S]*color: var\(--query-primary\)[\s\S]*background: var\(--query-primary-soft\)/)
  assert.doesNotMatch(view, /query-prompt-action:nth-child/)
  assert.doesNotMatch(view, /\.chat-card/)
  assert.doesNotMatch(view, /\.query-scope-panel/)
  assert.doesNotMatch(view, /\.input-area/)
  assert.doesNotMatch(view, /\.example-tag/)
  assert.doesNotMatch(view, /#2563eb/)
  assert.doesNotMatch(view, /#b45309/)
  assert.doesNotMatch(view, /linear-gradient\(180deg, #ffffff 0%, #f8fafc 100%\)/)
  assert.match(view, /min-height: 44px/)
  assert.match(view, /conversation-shell/)
  assert.match(view, /prompt-suggestion-grid/)
  assert.match(view, /command-composer/)
  assert.match(view, /is-composer-focused/)
  assert.match(view, /composeFocused/)
  assert.match(view, /submitOnEnter/)
  assert.match(view, /suggestionCards/)
  assert.match(view, /composerHintText/)
  assert.match(view, /composerStatusText/)
  assert.match(view, /新建对话/)
  assert.match(view, /清空当前/)
  assert.doesNotMatch(view, /query-command-center/)
  assert.doesNotMatch(view, /query-title-block/)
  assert.doesNotMatch(view, /自然语言数据工作台/)
  assert.doesNotMatch(view, /context-status-strip/)
  assert.doesNotMatch(view, /queryMetrics/)
  assert.doesNotMatch(view, /@media \(max-width: 1180px\)[^@]*\.welcome-message\s*{\s*grid-template-columns: 1fr/)
})

test("agentic mode is datasource-only and admin roles default into it", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(view, /const isDeptAdminOrAbove = computed/)
  assert.match(view, /applyRoleDefaultMode/)
  assert.match(view, /queryStore\.mode = "agentic"/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return Boolean\(queryStore\.selectedDatasourceId\)/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return activeDatasource\.value\?\.name \|\| "未选择数据源"/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return "数据源"/)
  assert.match(view, /queryStore\.mode === 'agentic'/)
  assert.doesNotMatch(view, /scopeOptions/)
  assert.doesNotMatch(view, /value:\s*"dataset"/)
  assert.doesNotMatch(view, /queryStore\.mode === ['"]explore['"]/)
  assert.doesNotMatch(view, /queryStore\.scopeMode === "dataset" \? "数据集" : "数据源"/)
  assert.match(store, /const datasetId = mode === "business" \? this\.selectedDatasetId : null/)
  assert.match(store, /agentTrace: response\.data\.agent_trace \|\| \[\]/)
  assert.match(store, /turn\.mode === "explore" \? "agentic"/)
})

test("agentic query exposes execution trace in chat messages", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")

  assert.match(bubble, /探索模式执行过程/)
  assert.match(bubble, /message\.status === 'sending'/)
  assert.match(bubble, /message\.agentTrace\?\.length/)
  assert.match(bubble, /trace-step/)
  assert.match(bubble, /trace-detail/)
  assert.match(bubble, /formatTraceDetail/)
  assert.match(bubble, /sql_execute_fix/)
  assert.match(bubble, /chat-error-line/)
  assert.match(store, /ask-stream/)
  assert.match(store, /ReadableStream/)
  assert.match(store, /getReader/)
  assert.match(store, /TextDecoder/)
  assert.match(store, /eventName === "trace"/)
  assert.match(store, /processStreamBlock/)
  assert.match(store, /if \(buffer\.trim\(\)\)/)
  assert.match(store, /errorDetail/)
  assert.match(store, /agent_trace/)
  assert.match(store, /payloadTrace\.length \? payloadTrace : current\?\.agentTrace \|\| \[\]/)
  assert.match(store, /agentTrace: errorAgentTrace/)
})

test("agentic query surfaces non-blocking assumptions and empty diagnostics", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(store, /export interface AgenticQueryNotes/)
  assert.match(store, /export interface EmptyDiagnostics/)
  assert.match(store, /agentNotes\?: AgenticQueryNotes/)
  assert.match(store, /emptyDiagnostics\?: EmptyDiagnostics/)
  assert.match(store, /agentNotes: payload\.agent_notes/)
  assert.match(store, /emptyDiagnostics: payload\.empty_diagnostics/)
  assert.match(bubble, /assumption-panel/)
  assert.match(bubble, /已按/)
  assert.match(bubble, /默认假设完成查询/)
  assert.match(bubble, /empty-diagnostics-panel/)
  assert.match(bubble, /未查到结果/)
  assert.match(bubble, /defineEmits/)
  assert.match(bubble, /use-refinement/)
  assert.match(bubble, /emitRefinement/)
  assert.match(bubble, /fill-refinement-button/)
  assert.match(bubble, /填入输入框/)
  assert.doesNotMatch(bubble, /@click="runRefinement\(action\.question\)"/)
  assert.doesNotMatch(bubble, /const runRefinement/)
  assert.match(view, /@use-refinement="applyRefinementDraft"/)
  assert.match(view, /applyRefinementDraft/)
  assert.match(view, /composerInputRef/)
  assert.match(view, /已填入建议问题/)
})

test("agentic trace panel is collapsible and expands failed step details", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /agentTracePanelOpen/)
  assert.match(bubble, /traceDetailOpen/)
  assert.match(bubble, /traceHistoryOpen/)
  assert.match(bubble, /latestTraceStep/)
  assert.match(bubble, /historicalTraceSteps/)
  assert.match(bubble, /traceCurrentStatusClass/)
  assert.match(bubble, /traceProgressPercent/)
  assert.match(bubble, /traceRunningText/)
  assert.match(bubble, /handleTracePanelChange/)
  assert.match(bubble, /defaultTraceDetailNames/)
  assert.match(bubble, /el-collapse v-model="agentTracePanelOpen" class="agent-trace-collapse"/)
  assert.match(bubble, /agent-trace-compact/)
  assert.match(bubble, /trace-summary-strip/)
  assert.match(bubble, /trace-summary-main/)
  assert.match(bubble, /trace-summary-chips/)
  assert.match(bubble, /trace-summary-chip/)
  assert.match(bubble, /trace-progress-line/)
  assert.match(bubble, /trace-latest-row/)
  assert.match(bubble, /trace-history-list/)
  assert.match(bubble, /trace-history-row/)
  assert.match(bubble, /trace-row-message/)
  assert.match(bubble, /trace-stage-pill/)
  assert.match(bubble, /trace-step-index/)
  assert.match(bubble, /completedTraceCount.*agentTraceSteps\.length/)
  assert.match(bubble, /历史步骤/)
  assert.match(bubble, /trace-step-dot/)
  assert.match(bubble, /trace-history-collapse/)
  assert.match(bubble, /el-collapse v-model="traceDetailOpen" class="trace-detail-collapse"/)
  assert.doesNotMatch(bubble, /trace-status-metrics/)
  assert.doesNotMatch(bubble, /trace-current-card/)
  assert.match(bubble, /traceSummary/)
  assert.match(bubble, /props\.message\.status === "success"/)
  assert.match(bubble, /失败步骤自动展开/)
})

test("agentic query carries chart spec into the chat chart renderer", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")
  const chart = read("src/components/MessageChart.vue")

  assert.match(store, /export interface ChartSpec/)
  assert.match(store, /chartSpec\?: ChartSpec/)
  assert.match(store, /chartSpec: payload\.chart_spec/)
  assert.match(store, /chartSpec: response\.data\.chart_spec/)
  assert.match(bubble, /:chart-spec="message\.chartSpec"/)
  assert.match(chart, /chartSpec\?: ChartSpec/)
  assert.match(chart, /applyChartSpec/)
})

test("query result operations include generated result entry without row field summary", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /analysis-action-card/)
  assert.match(bubble, /结果操作/)
  assert.match(bubble, /生成结果/)
  assert.match(bubble, /查看可视化、明细、SQL 和总结/)
  assert.match(bubble, /openResultDetail\('chart'\)/)
  assert.match(bubble, /openResultDetail\('table'\)/)
  assert.match(bubble, /openResultDetail\('sql'\)/)
  assert.match(bubble, /openResultDetail\('summary'\)/)
  assert.match(bubble, /result-inline-toolbar/)
  assert.doesNotMatch(bubble, /analysisMetaText/)
  assert.doesNotMatch(bubble, /result-layer-card/)
  assert.doesNotMatch(bubble, /result-layer-stats/)
  assert.doesNotMatch(bubble, /result-table-entry-card/)
  assert.doesNotMatch(bubble, /行结果 ·/)
  assert.doesNotMatch(bubble, /个字段/)
  assert.doesNotMatch(bubble, /完整明细已放入结果详情/)
})

test("attribution panel surfaces llm enhanced state", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /llm_enhanced/)
  assert.match(bubble, /大模型增强/)
  assert.match(bubble, /attributionEnhancementLabel/)
  assert.doesNotMatch(bubble, /insightEnhancementLabel/)
})

test("smart result actions expose result, action item, attribution, and metric drafting", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /异常归因/)
  assert.match(bubble, /贡献分析/)
  assert.match(bubble, /保存为指标/)
  assert.match(bubble, /生成行动项/)
  assert.match(bubble, /把这次分析结论交给责任人跟踪处理/)
  assert.match(bubble, /analysis-action-card/)
  assert.match(bubble, /analysis-action-grid/)
  assert.match(bubble, /analysis-action-tile/)
  assert.match(bubble, /analysis-action-tile--action/)
  assert.match(bubble, /analysis-action-icon--action/)
  assert.match(bubble, /analysisResultPanels/)
  assert.match(bubble, /attribution-panel-collapse/)
  assert.match(bubble, /analysisStatusText/)
  assert.match(bubble, /attributionPrecheckResult/)
  assert.match(bubble, /attributionPrecheckLoading/)
  assert.match(bubble, /runAttributionPrecheck/)
  assert.match(bubble, /\/api\/insights\/anomaly-precheck/)
  assert.match(bubble, /watch\(\s*\(\) => hasResult\.value/)
  assert.match(bubble, /if \(ready && !props\.message\.fromHistory\) void runAttributionPrecheck\(\)/)
  assert.match(bubble, /历史结果已加载，可按需分析/)
  assert.match(bubble, /attributionActionLabel/)
  assert.match(bubble, /attributionActionDescription/)
  assert.match(bubble, /precheck-status-chip/)
  assert.match(bubble, /metricDraftCompletionItems/)
  assert.match(bubble, /metric-draft-checklist/)
  assert.match(bubble, /保存为指标草稿/)
  assert.match(bubble, /保存后会进入指标草稿/)
  assert.match(bubble, /openActionDialog/)
  assert.match(bubble, /runAttribution/)
  assert.match(bubble, /openMetricDraftDrawer/)
  assert.match(bubble, /summary-box[\s\S]+analysis-action-card[\s\S]+result-inline-panel/)
  assert.doesNotMatch(bubble, /decision-action-bar/)
  assert.doesNotMatch(bubble, /自动洞察/)
  assert.doesNotMatch(bubble, /保存为洞察/)
  assert.doesNotMatch(bubble, /洞察标题/)
  assert.doesNotMatch(bubble, /洞察将保存到查询洞察列表/)
  assert.doesNotMatch(bubble, /runAutoInsights/)
  assert.doesNotMatch(bubble, /openInsightDialog/)
  assert.doesNotMatch(bubble, /saveInsightDialogVisible/)
  assert.doesNotMatch(bubble, /\/api\/query\/save-insight/)
  assert.doesNotMatch(bubble, /\/api\/insights\/auto-insights/)
  assert.match(bubble, /<el-tree-select/)
  assert.match(bubble, /actionAssignableTree/)
  assert.match(bubble, /\/api\/users\/assignable/)
  assert.match(bubble, /按部门选择负责人/)
  assert.doesNotMatch(bubble, /负责人 ID/)
  assert.doesNotMatch(bubble, /<el-input-number v-model="actionForm\.owner_id"/)
})

test("smart query result uses layered detail interactions", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /resultDetailVisible/)
  assert.match(bubble, /resultDetailTab/)
  assert.match(bubble, /openResultDetail/)
  assert.match(bubble, /result-detail-dialog/)
  assert.match(bubble, /result-detail-tabs/)
  assert.match(bubble, /result-detail-pane/)
  assert.match(bubble, /result-detail-summary/)
  assert.match(bubble, /analysis-action-tile--result/)
  assert.match(bubble, /name="chart"/)
  assert.match(bubble, /name="table"/)
  assert.match(bubble, /name="sql"/)
  assert.match(bubble, /MessageChart[\s\S]+MessageTable/)
  assert.match(bubble, /生成结果/)
  assert.match(bubble, /数据明细/)
  assert.match(bubble, /SQL/)
  assert.doesNotMatch(bubble, /result-layer-card/)
  assert.doesNotMatch(bubble, /result-table-entry-card/)
  assert.doesNotMatch(bubble, /class="table-container result-inline-panel"/)
  assert.doesNotMatch(bubble, /数据预览/)
})

test("explore result can be converted into an editable metric draft", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")
  const datasetCenter = read("src/views/DatasetCenter.vue")
  const main = read("src/main.ts")

  assert.match(bubble, /保存为指标/)
  assert.match(bubble, /metricDraftDrawerVisible/)
  assert.match(bubble, /metricDraftDatasetMissing/)
  assert.match(bubble, /指标草稿/)
  assert.match(bubble, /\/api\/metrics\/from-query\/draft/)
  assert.match(bubble, /\/api\/metrics\/from-query/)
  assert.match(bubble, /selected_metric_column/)
  assert.match(bubble, /source_dataset_id/)
  assert.match(bubble, /绑定数据集/)
  assert.match(bubble, /当前数据源下没有可绑定的同源数据集/)
  assert.match(bubble, /创建基础数据集/)
  assert.match(bubble, /openDatasetBuilderForMetric/)
  assert.match(bubble, /DatasetCenter/)
  assert.match(bubble, /datasetBuilderVisible/)
  assert.match(bubble, /handleMetricDatasetCreated/)
  assert.match(bubble, /embedded/)
  assert.match(bubble, /auto-create/)
  assert.match(bubble, /preferred-datasource-id/)
  assert.match(bubble, /suppressGlobalError: true/)
  assert.doesNotMatch(bubble, /path: "\/data-development"/)
  assert.match(bubble, /dataset_id: metricDraftForm\.dataset_id/)
  assert.match(bubble, /source_query_history_id/)
  assert.match(bubble, /pending_review/)
  assert.match(store, /datasourceId\?: number \| null/)
  assert.match(store, /datasourceId: datasourceId/)
  assert.match(store, /datasourceId: turn\.datasource_id/)
  assert.match(datasetCenter, /embedded\?: boolean/)
  assert.match(datasetCenter, /autoCreate\?: boolean/)
  assert.match(datasetCenter, /preferredDatasourceId\?: number \| null/)
  assert.match(datasetCenter, /dataset-drawer--embedded/)
  assert.match(datasetCenter, /dataset-drawer-modal--embedded/)
  assert.match(datasetCenter, /embedded-designer-shell/)
  assert.match(datasetCenter, /grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(datasetCenter, /overflow-x: hidden/)
  assert.match(datasetCenter, /defineEmits/)
  assert.match(datasetCenter, /emit\("saved"/)
  assert.match(datasetCenter, /route\.query\.create === "dataset"/)
  assert.match(datasetCenter, /openCreate\(routeDatasourceId\.value\)/)
  assert.match(datasetCenter, /delete nextQuery\.create/)
  assert.match(main, /suppressGlobalError/)
  assert.match(main, /if \(suppressGlobalError\) return Promise\.reject\(error\)/)
})

test("natural-language dashboard chart creation uses agentic mode", () => {
  const dashboard = read("src/views/DashboardCenter.vue")

  assert.match(dashboard, /canUseAgenticMode/)
  assert.match(dashboard, /探索模式仅部门管理员及以上可用/)
  assert.match(dashboard, /mode: "agentic"/)
  assert.doesNotMatch(dashboard, /mode: "explore"/)
  assert.doesNotMatch(dashboard, /mode: "text2sql"/)
})
