import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { test } from "node:test"

const root = resolve(import.meta.dirname, "..")
const read = (path) => readFileSync(resolve(root, path), "utf8")

test("smart query exposes only business and agentic modes", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")
  const authStore = read("src/store/auth.ts")

  assert.match(view, /业务问数/)
  assert.match(view, /探索模式/)
  assert.match(view, /canUseAgenticMode/)
  assert.match(view, /label="agentic"/)
  assert.match(view, /useAuthStore/)
  assert.match(authStore, /canUseAgenticMode/)
  assert.match(authStore, /dept_admin/)
  assert.match(store, /QueryMode = "business" \| "agentic"/)
  assert.match(store, /mode: "business" as QueryMode/)
  assert.doesNotMatch(view, /闲聊模式/)
  assert.doesNotMatch(view, /Agentic 问数/)
  assert.doesNotMatch(view, /label="explore"/)
  assert.doesNotMatch(view, /label="chat"/)
  assert.doesNotMatch(store, /"chat"/)
})

test("business query defaults to dataset scope and keeps SQL in result details", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(store, /scopeMode: "dataset" as QueryScopeMode/)
  assert.match(view, /queryStore\.mode === "business"/)
  assert.match(view, /业务问数必须选择数据集/)
  assert.doesNotMatch(view, /默认使用可信指标和数据集语义层/)
  assert.match(bubble, /openResultDetail\('sql'\)/)
  assert.match(bubble, /result-detail-sql/)
  assert.doesNotMatch(bubble, /技术细节 \/ SQL 查询语句/)
  assert.doesNotMatch(bubble, /class="sql-collapse"/)
  assert.doesNotMatch(bubble, /探索结果，非认证口径/)
  assert.doesNotMatch(bubble, /message\.mode === ['"]explore['"]/)
})

test("query history provides searchable CRUD controls and a new conversation entry", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(view, /新建对话/)
  assert.match(view, /startNewConversation/)
  assert.match(view, /queryStore\.clearMessages\(\)/)
  assert.match(view, /historyLoadingId/)
  assert.match(view, /isRestoringHistory/)
  assert.match(view, /history-loading-icon/)
  assert.match(view, /if \(historyLoadingId\.value \|\| queryStore\.loading\) return/)
  assert.match(view, /try[\s\S]+queryStore\.loadHistoryDetail\(item\.id\)[\s\S]+finally[\s\S]+historyLoadingId\.value = null/)
  assert.match(view, /refreshHistoryForScope/)
  assert.match(view, /if \(isRestoringHistory\.value\) return/)
  assert.match(view, /historySearch/)
  assert.match(view, /historyFilter/)
  assert.match(store, /params\.mode = this\.mode/)
  assert.match(store, /await axios\.delete\("\/api\/query\/history", \{ params \}\)/)
  assert.match(store, /mode\?: QueryMode/)
  assert.match(view, /historyModeLabel\(item\)/)
  assert.match(view, /historyModeTagType\(item\)/)
  assert.match(view, /filteredHistory/)
  assert.match(view, /historyEmptyDescription/)
  assert.match(view, /confirmDeleteHistoryItem/)
  assert.match(view, /ElMessageBox\.confirm/)
  assert.match(view, /history-empty-actions/)
  assert.match(view, /收藏/)
  assert.match(view, /清空历史/)
  assert.match(view, /formatHistoryDate/)
  assert.match(store, /currentConversationRootHistoryId/)
  assert.match(store, /currentConversationContextKey/)
  assert.match(store, /buildConversationContextKey/)
  assert.match(store, /const canContinueConversation = this\.currentConversationContextKey === conversationContextKey/)
  assert.match(store, /const effectiveParentHistoryId = parentHistoryId \?\? \(canContinueConversation \? this\.currentConversationRootHistoryId : null\)/)
  assert.match(store, /parent_history_id: effectiveParentHistoryId \|\| null/)
  assert.match(store, /this\.currentConversationContextKey = conversationContextKey/)
  assert.match(store, /conversationRootId/)
  assert.match(store, /conversationDatasourceId/)
  assert.match(store, /datasource_id/)
  assert.match(store, /data\.conversation/)
  assert.match(store, /fromHistory\?: boolean/)
  assert.match(store, /fromHistory: true/)
})

test("smart query workspace uses modern guided interactions", () => {
  const view = read("src/views/SmartQuery.vue")
  const layout = read("src/layouts/MainLayout.vue")

  assert.match(view, /query-workspace/)
  assert.match(view, /query-compact-workspace/)
  assert.match(view, /query-workbench-toolbar/)
  assert.match(view, /<Teleport to="#smart-query-header-actions"/)
  assert.match(view, /query-header-teleport-toolbar/)
  assert.match(view, /\.query-header-teleport-toolbar\s*{[\s\S]*--query-primary: #0f766e/)
  assert.match(view, /\.query-header-teleport-toolbar :deep\(\.el-button\)/)
  assert.match(view, /\.query-header-teleport-toolbar :deep\(\.el-tag\)/)
  assert.match(layout, /id="smart-query-header-actions"/)
  assert.match(layout, /smart-query-header-actions-target/)
  assert.match(view, /query-mode-switcher/)
  assert.match(view, /query-toolbar-actions/)
  assert.match(view, /query-toolbar-scope/)
  assert.match(view, /query-mode-switcher[\s\S]+query-toolbar-scope[\s\S]+query-toolbar-actions/)
  assert.match(view, /class="mode-tabs query-mode-switcher"/)
  assert.match(view, /query-history-left-layout/)
  assert.match(view, /grid-template-areas: "history chat"/)
  assert.match(view, /\.conversation-shell\s*{[\s\S]*grid-area: chat/)
  assert.match(view, /\.query-side-panel\s*{[\s\S]*grid-area: history/)
  assert.match(view, /welcome-panel/)
  assert.match(view, /query-start-panel/)
  assert.match(view, /welcome-primary/)
  assert.match(view, /query-start-copy/)
  assert.match(view, /prompt-suggestion-rail/)
  assert.match(view, /query-prompt-list/)
  assert.match(view, /query-prompt-action/)
  assert.match(view, /--query-primary: #0f766e/)
  assert.match(view, /\.smart-query-page :deep\(\.el-button\)/)
  assert.match(view, /\.smart-query-page :deep\(\.el-tag\)/)
  assert.match(view, /\.scope-select :deep\(\.el-select__wrapper\)/)
  assert.match(view, /\.history-filter[\s\S]+var\(--query-primary\)/)
  assert.match(view, /\.history-filter :deep\(\.el-segmented__item\.is-selected\)[\s\S]+color: #ffffff/)
  assert.match(view, /\.history-filter :deep\(\.el-segmented__item\.is-selected \.el-segmented__item-label\)[\s\S]+color: #ffffff/)
  assert.match(view, /popper-class="query-scope-popper"/)
  assert.match(view, /:global\(\.query-scope-popper\)/)
  assert.match(view, /\.welcome-message\s*{[\s\S]*width: min\(100%, 760px\)[\s\S]*grid-template-columns: 1fr/)
  assert.doesNotMatch(view, /grid-template-columns: minmax\(220px, 0\.72fr\) minmax\(340px, 1\.28fr\)/)
  assert.match(view, /\.welcome-primary\s*{[\s\S]*background: var\(--query-surface\)/)
  assert.match(view, /\.prompt-suggestion-card \.el-icon\s*{[\s\S]*color: var\(--query-primary\)[\s\S]*background: var\(--query-primary-soft\)/)
  assert.doesNotMatch(view, /query-prompt-action:nth-child/)
  assert.doesNotMatch(view, /\.chat-card/)
  assert.doesNotMatch(view, /\.query-scope-panel/)
  assert.doesNotMatch(view, /\.input-area/)
  assert.doesNotMatch(view, /\.example-tag/)
  assert.doesNotMatch(view, /#2563eb/)
  assert.doesNotMatch(view, /#b45309/)
  assert.doesNotMatch(view, /linear-gradient\(180deg, #ffffff 0%, #f8fafc 100%\)/)
  assert.match(view, /min-height: 44px/)
  assert.match(view, /conversation-shell/)
  assert.match(view, /prompt-suggestion-grid/)
  assert.match(view, /command-composer/)
  assert.match(view, /is-composer-focused/)
  assert.match(view, /composeFocused/)
  assert.match(view, /submitOnEnter/)
  assert.match(view, /composer-input-row/)
  assert.match(view, /composer-input-row[\s\S]+composer-input[\s\S]+composer-submit/)
  assert.match(view, /\.composer-input-row\s*{[\s\S]*align-items: stretch/)
  assert.match(view, /\.composer-input\s*{[\s\S]*display: flex/)
  assert.match(view, /\.composer-submit\s*{[\s\S]*height: auto[\s\S]*align-self: stretch/)
  assert.doesNotMatch(view, /composer-topline/)
  assert.doesNotMatch(view, /composer-footer/)
  assert.doesNotMatch(view, /composer-hints/)
  assert.doesNotMatch(view, /composerStatusText/)
  assert.match(view, /suggestionCards/)
  assert.match(view, /composerHintText/)
  assert.match(view, /新建对话/)
  assert.match(view, /清空当前/)
  assert.doesNotMatch(view, /query-command-center/)
  assert.doesNotMatch(view, /query-title-block/)
  assert.doesNotMatch(view, /自然语言数据工作台/)
  assert.doesNotMatch(view, /context-status-strip/)
  assert.doesNotMatch(view, /queryMetrics/)
  assert.doesNotMatch(view, /@media \(max-width: 1180px\)[^@]*\.welcome-message\s*{\s*grid-template-columns: 1fr/)
})

test("smart query starts centered and opens result tabs from the summary", () => {
  const view = read("src/views/SmartQuery.vue")
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(view, /query-dialog-stage/)
  assert.match(view, /isNewConversation/)
  assert.match(view, /hasConversation/)
  assert.match(view, /'is-new-dialog': isNewConversation/)
  assert.match(view, /'has-conversation': hasConversation/)
  assert.match(view, /query-composer-dock-enter/)
  assert.match(view, /@open-result="openResultDock\(message, \$event\)"/)
  assert.match(view, /selectedResultMessage/)
  assert.match(view, /resultDockTab/)
  assert.match(view, /query-result-dock/)
  assert.match(view, /query-result-tabs/)
  assert.match(view, /closeResultDock/)
  assert.match(view, /label="图表" name="chart"/)
  assert.match(view, /label="明细数据" name="table"/)
  assert.match(view, /label="SQL" name="sql"/)
  assert.match(view, /MessageChart/)
  assert.match(view, /MessageTable/)

  assert.match(bubble, /compactResult/)
  assert.match(bubble, /showAssistantContent/)
  assert.match(bubble, /showResultQuickActions/)
  assert.match(bubble, /summary-box--clickable/)
  assert.match(bubble, /const showInlineResultPreview = computed\(\(\) => hasResult\.value\)/)
  assert.match(bubble, /class="chart-container result-inline-panel"/)
  assert.match(bubble, /openResultFromSummary/)
  assert.match(bubble, /emit\("open-result", tab\)/)
  assert.match(bubble, /@keydown\.enter\.prevent="openResultFromSummary"/)
  assert.match(bubble, /v-if="showResultQuickActions"/)
  assert.match(bubble, /v-if="showInlineResultPreview"/)
})

test("agentic mode is datasource-only and admin roles default into it", () => {
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(view, /const isDeptAdminOrAbove = computed/)
  assert.match(view, /applyRoleDefaultMode/)
  assert.match(view, /queryStore\.mode = "agentic"/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return Boolean\(queryStore\.selectedDatasourceId\)/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return activeDatasource\.value\?\.name \|\| "未选择数据源"/)
  assert.match(view, /if \(queryStore\.mode === "agentic"\) return "探索数据源"/)
  assert.match(view, /queryStore\.mode === 'agentic'/)
  assert.doesNotMatch(view, /scopeOptions/)
  assert.doesNotMatch(view, /value:\s*"dataset"/)
  assert.doesNotMatch(view, /queryStore\.mode === ['"]explore['"]/)
  assert.doesNotMatch(view, /queryStore\.scopeMode === "dataset" \? "数据集" : "数据源"/)
  assert.match(store, /const datasetId = mode === "business" \? this\.selectedDatasetId : null/)
  assert.match(store, /agentTrace: response\.data\.agent_trace \|\| \[\]/)
  assert.match(store, /turn\.mode === "explore" \? "agentic"/)
})

test("agentic query exposes execution trace in chat messages", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")

  assert.match(bubble, /探索模式执行过程/)
  assert.match(bubble, /message\.status === 'sending'/)
  assert.match(bubble, /message\.agentTrace\?\.length/)
  assert.match(bubble, /trace-step/)
  assert.match(bubble, /trace-detail/)
  assert.match(bubble, /formatTraceDetail/)
  assert.match(bubble, /sql_execute_fix/)
  assert.match(bubble, /chat-error-line/)
  assert.match(store, /ask-stream/)
  assert.match(store, /ReadableStream/)
  assert.match(store, /getReader/)
  assert.match(store, /TextDecoder/)
  assert.match(store, /eventName === "trace"/)
  assert.match(store, /processStreamBlock/)
  assert.match(store, /if \(buffer\.trim\(\)\)/)
  assert.match(store, /errorDetail/)
  assert.match(store, /agent_trace/)
  assert.match(store, /payloadTrace\.length \? payloadTrace : current\?\.agentTrace \|\| \[\]/)
  assert.match(store, /agentTrace: errorAgentTrace/)
})

test("agentic query surfaces non-blocking assumptions and empty diagnostics", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const view = read("src/views/SmartQuery.vue")
  const store = read("src/store/query.ts")

  assert.match(store, /export interface AgenticQueryNotes/)
  assert.match(store, /export interface EmptyDiagnostics/)
  assert.match(store, /agentNotes\?: AgenticQueryNotes/)
  assert.match(store, /emptyDiagnostics\?: EmptyDiagnostics/)
  assert.match(store, /agentNotes: payload\.agent_notes/)
  assert.match(store, /emptyDiagnostics: payload\.empty_diagnostics/)
  assert.match(bubble, /agentNotesDialogVisible/)
  assert.match(bubble, /agent-notes-dialog/)
  assert.match(bubble, /openAgentNotesDialog/)
  assert.match(bubble, /result-mini-action--notes/)
  assert.match(bubble, /已按/)
  assert.match(bubble, /默认假设完成查询/)
  assert.match(bubble, /empty-diagnostics-panel/)
  assert.match(bubble, /未查到结果/)
  assert.match(bubble, /defineEmits/)
  assert.match(bubble, /use-refinement/)
  assert.match(bubble, /emitRefinement/)
  assert.match(bubble, /assumptionRefinementSelection/)
  assert.match(bubble, /assumptionRefinementDrafts/)
  assert.match(bubble, /assumptionBatchQuestion/)
  assert.match(bubble, /runAssumptionBatchRefinement/)
  assert.match(bubble, /assumption-refinement-workbench/)
  assert.match(bubble, /按这些澄清重新查询/)
  assert.match(bubble, /refinement-draft-editor/)
  assert.match(bubble, /queryStore\.ask\(question, props\.message\.mode \|\| "business", undefined, props\.message\.historyId\)/)
  assert.doesNotMatch(bubble, /@click="runRefinement\(action\.question\)"/)
  assert.doesNotMatch(bubble, /const runRefinement/)
  assert.doesNotMatch(bubble, /class="fill-refinement-button" @click="emitRefinement\(action\.question\)"/)
  assert.match(view, /@use-refinement="applyRefinementDraft"/)
  assert.match(view, /applyRefinementDraft/)
  assert.match(view, /composerInputRef/)
  assert.match(view, /已填入建议问题/)
})

test("agentic trace dialog uses a horizontal stepper and shows selected details inline", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /agentTraceDialogVisible/)
  assert.match(bubble, /agent-trace-dialog/)
  assert.match(bubble, /openAgentTraceDialog/)
  assert.match(bubble, /result-mini-action--trace/)
  assert.match(bubble, /agentTracePanelOpen/)
  assert.match(bubble, /latestTraceStep/)
  assert.match(bubble, /traceCurrentStatusClass/)
  assert.match(bubble, /traceProgressPercent/)
  assert.match(bubble, /traceRunningText/)
  assert.match(bubble, /activeTraceStepIndex/)
  assert.match(bubble, /selectedTraceStep/)
  assert.match(bubble, /selectTraceStep/)
  assert.match(bubble, /handleTracePanelChange/)
  assert.match(bubble, /el-collapse v-model="agentTracePanelOpen" class="agent-trace-collapse"/)
  assert.match(bubble, /agent-trace-compact/)
  assert.match(bubble, /trace-summary-strip/)
  assert.match(bubble, /trace-summary-main/)
  assert.match(bubble, /trace-summary-chips/)
  assert.match(bubble, /trace-summary-chip/)
  assert.match(bubble, /trace-progress-line/)
  assert.match(bubble, /trace-stepper/)
  assert.match(bubble, /trace-stepper-track/)
  assert.match(bubble, /trace-stepper-node/)
  assert.match(bubble, /trace-stepper-circle/)
  assert.match(bubble, /trace-stepper-icon/)
  assert.match(bubble, /traceStageIcon/)
  assert.match(bubble, /<component :is="traceStageIcon\(step\.stage\)" \/>/)
  assert.match(bubble, /trace-stepper-node--active/)
  assert.match(bubble, /trace-selected-panel/)
  assert.match(bubble, /trace-selected-meta/)
  assert.match(bubble, /trace-detail-panel/)
  assert.match(bubble, /trace-row-message/)
  assert.match(bubble, /trace-stage-pill/)
  assert.match(bubble, /trace-step-index/)
  assert.match(bubble, /completedTraceCount.*agentTraceSteps\.length/)
  assert.doesNotMatch(bubble, /点击上方圆形节点/)
  assert.doesNotMatch(bubble, /历史步骤/)
  assert.doesNotMatch(bubble, /trace-history-list/)
  assert.doesNotMatch(bubble, /trace-history-row/)
  assert.doesNotMatch(bubble, /trace-detail-collapse/)
  assert.doesNotMatch(bubble, /defaultTraceDetailNames/)
  assert.doesNotMatch(bubble, /失败步骤自动展开/)
  assert.match(bubble, /trace-step-dot/)
  assert.doesNotMatch(bubble, /trace-status-metrics/)
  assert.doesNotMatch(bubble, /trace-current-card/)
  assert.match(bubble, /traceSummary/)
  assert.match(bubble, /props\.message\.status === "success"/)
  assert.doesNotMatch(bubble, /<span class="trace-step-index">\{\{ index \+ 1 \}\}<\/span>/)
})

test("agentic query carries chart spec into the chat chart renderer", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")
  const chart = read("src/components/MessageChart.vue")

  assert.match(store, /export interface ChartSpec/)
  assert.match(store, /chartSpec\?: ChartSpec/)
  assert.match(store, /chartSpec: payload\.chart_spec/)
  assert.match(store, /chartSpec: response\.data\.chart_spec/)
  assert.match(bubble, /:chart-spec="message\.chartSpec"/)
  assert.match(chart, /chartSpec\?: ChartSpec/)
  assert.match(chart, /applyChartSpec/)
})

test("inline chat result preview keeps a stable chart width", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /'chat-bubble--with-result': showInlineResultPreview/)
  assert.match(bubble, /\.chat-bubble--assistant\.chat-bubble--with-result\s*{[\s\S]*width: min\(100%, 980px\)/)
  assert.match(bubble, /\.chat-bubble--with-result \.chat-content\s*{[\s\S]*flex: 1 1 auto/)
  assert.match(bubble, /\.result-inline-panel\s*{[\s\S]*width: 100%/)
  assert.match(bubble, /\.result-inline-panel\s*{[\s\S]*min-width: 0/)
})

test("business query result adjusts semantic metrics and dimensions inline above the chart", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")

  assert.match(store, /export interface BusinessSemanticContext/)
  assert.match(store, /semanticContext\?: BusinessSemanticContext/)
  assert.match(store, /semanticContext: payload\.semantic_context/)
  assert.match(store, /semanticContext: response\.data\.semantic_context/)
  assert.match(store, /semanticContext: turn\.semantic_context/)
  assert.match(bubble, /business-semantic-bar/)
  assert.match(bubble, /business-semantic-control-panel/)
  assert.match(bubble, /semanticMetricChips/)
  assert.match(bubble, /semanticDimensionChips/)
  assert.match(bubble, /semanticFilterChips/)
  assert.match(bubble, /semanticSelectedMetricId/)
  assert.match(bubble, /semanticSelectedDimensionIds/)
  assert.match(bubble, /toggleSemanticDimension/)
  assert.match(bubble, /applySemanticContextQuery/)
  assert.match(bubble, /queryStore\.runSemanticQuery/)
  assert.match(bubble, /业务口径/)
  assert.match(bubble, /指标/)
  assert.match(bubble, /维度/)
  assert.match(bubble, /调整维度/)
  assert.doesNotMatch(bubble, /semantic-context-dialog/)
  assert.doesNotMatch(bubble, /semanticContextDialogVisible/)
  assert.doesNotMatch(bubble, /openSemanticContextDialog/)
})

test("query result operations include generated result entry without row field summary", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /compact-result-actions/)
  assert.match(bubble, /result-mini-action-button/)
  assert.match(bubble, /result-mini-action--metric/)
  assert.match(bubble, /result-mini-action--attribution/)
  assert.match(bubble, /result-mini-action--action/)
  assert.match(bubble, /openResultDetail\('chart'\)/)
  assert.match(bubble, /openResultDetail\('table'\)/)
  assert.match(bubble, /openResultDetail\('sql'\)/)
  assert.match(bubble, /openResultDetail\('summary'\)/)
  assert.match(bubble, /result-inline-toolbar/)
  assert.doesNotMatch(bubble, /analysis-action-card/)
  assert.doesNotMatch(bubble, /analysis-action-grid/)
  assert.doesNotMatch(bubble, /analysis-action-tile/)
  assert.doesNotMatch(bubble, /analysisMetaText/)
  assert.doesNotMatch(bubble, /result-layer-card/)
  assert.doesNotMatch(bubble, /result-layer-stats/)
  assert.doesNotMatch(bubble, /result-table-entry-card/)
  assert.doesNotMatch(bubble, /行结果 ·/)
  assert.doesNotMatch(bubble, /个字段/)
  assert.doesNotMatch(bubble, /完整明细已放入结果详情/)
})

test("attribution panel surfaces llm enhanced state", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /llm_enhanced/)
  assert.match(bubble, /大模型增强/)
  assert.match(bubble, /attributionEnhancementLabel/)
  assert.doesNotMatch(bubble, /insightEnhancementLabel/)
})

test("smart result actions expose result, action item, attribution, and metric drafting", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /异常归因/)
  assert.match(bubble, /贡献分析/)
  assert.match(bubble, /保存为指标/)
  assert.match(bubble, /生成行动项/)
  assert.match(bubble, /compact-result-actions/)
  assert.match(bubble, /result-mini-action-button/)
  assert.match(bubble, /result-mini-action--notes/)
  assert.match(bubble, /result-mini-action--trace/)
  assert.match(bubble, /result-mini-action--action/)
  assert.match(bubble, /result-mini-action--attribution/)
  assert.match(bubble, /attribution-beta-badge/)
  assert.match(bubble, /Beta/)
  assert.match(bubble, /result-mini-action--metric/)
  assert.match(bubble, /metric-beta-badge/)
  assert.match(bubble, /result-mini-action-beta-badge/)
  assert.match(bubble, /agentNotesDialogVisible/)
  assert.match(bubble, /agentTraceDialogVisible/)
  assert.match(bubble, /attributionDialogVisible/)
  assert.match(bubble, /agent-notes-dialog/)
  assert.match(bubble, /agent-trace-dialog/)
  assert.match(bubble, /attribution-dialog/)
  assert.match(bubble, /analysisResultPanels/)
  assert.match(bubble, /attribution-panel-collapse/)
  assert.match(bubble, /analysisStatusText/)
  assert.match(bubble, /attributionPrecheckResult/)
  assert.match(bubble, /attributionPrecheckLoading/)
  assert.match(bubble, /runAttributionPrecheck/)
  assert.match(bubble, /\/api\/insights\/anomaly-precheck/)
  assert.match(bubble, /watch\(\s*\(\) => hasResult\.value/)
  assert.match(bubble, /if \(ready && !props\.message\.fromHistory\) void runAttributionPrecheck\(\)/)
  assert.match(bubble, /历史结果已加载，可按需分析/)
  assert.match(bubble, /attributionActionLabel/)
  assert.match(bubble, /attributionActionDescription/)
  assert.match(bubble, /metricDraftCompletionItems/)
  assert.match(bubble, /metric-draft-checklist/)
  assert.match(bubble, /保存为指标草稿/)
  assert.match(bubble, /保存后会进入指标草稿/)
  assert.match(bubble, /openActionDialog/)
  assert.match(bubble, /openAttributionDialog/)
  assert.match(bubble, /runAttribution/)
  assert.match(bubble, /openMetricDraftDrawer/)
  assert.match(bubble, /<!-- 查询结果图表 -->[\s\S]+class="chart-container result-inline-panel"[\s\S]+<!-- 分析总结 -->[\s\S]+class="compact-result-actions"/)
  assert.doesNotMatch(bubble, /<!-- 分析总结 -->[\s\S]+class="compact-result-actions"[\s\S]+<!-- 查询结果图表 -->/)
  assert.doesNotMatch(bubble, /把这次分析结论交给责任人跟踪处理/)
  assert.doesNotMatch(bubble, /analysis-action-card/)
  assert.doesNotMatch(bubble, /analysis-action-grid/)
  assert.doesNotMatch(bubble, /analysis-action-tile/)
  assert.doesNotMatch(bubble, /decision-action-bar/)
  assert.doesNotMatch(bubble, /自动洞察/)
  assert.doesNotMatch(bubble, /保存为洞察/)
  assert.doesNotMatch(bubble, /洞察标题/)
  assert.doesNotMatch(bubble, /洞察将保存到查询洞察列表/)
  assert.doesNotMatch(bubble, /runAutoInsights/)
  assert.doesNotMatch(bubble, /openInsightDialog/)
  assert.doesNotMatch(bubble, /saveInsightDialogVisible/)
  assert.doesNotMatch(bubble, /\/api\/query\/save-insight/)
  assert.doesNotMatch(bubble, /\/api\/insights\/auto-insights/)
  assert.match(bubble, /<el-tree-select/)
  assert.match(bubble, /actionAssignableTree/)
  assert.match(bubble, /\/api\/users\/assignable/)
  assert.match(bubble, /按部门选择负责人/)
  assert.doesNotMatch(bubble, /负责人 ID/)
  assert.doesNotMatch(bubble, /<el-input-number v-model="actionForm\.owner_id"/)
})

test("smart query result uses layered detail interactions", () => {
  const bubble = read("src/components/ChatBubble.vue")

  assert.match(bubble, /resultDetailVisible/)
  assert.match(bubble, /resultDetailTab/)
  assert.match(bubble, /openResultDetail/)
  assert.match(bubble, /result-detail-dialog/)
  assert.match(bubble, /result-detail-tabs/)
  assert.match(bubble, /result-detail-pane/)
  assert.match(bubble, /result-detail-summary/)
  assert.match(bubble, /compact-result-actions/)
  assert.match(bubble, /name="chart"/)
  assert.match(bubble, /name="table"/)
  assert.match(bubble, /name="sql"/)
  assert.match(bubble, /MessageChart[\s\S]+MessageTable/)
  assert.match(bubble, /可视化预览/)
  assert.match(bubble, /数据明细/)
  assert.match(bubble, /SQL/)
  assert.doesNotMatch(bubble, /result-layer-card/)
  assert.doesNotMatch(bubble, /result-table-entry-card/)
  assert.doesNotMatch(bubble, /class="table-container result-inline-panel"/)
  assert.doesNotMatch(bubble, /数据预览/)
})

test("explore result can be converted into an editable metric draft", () => {
  const bubble = read("src/components/ChatBubble.vue")
  const store = read("src/store/query.ts")
  const datasetCenter = read("src/views/DatasetCenter.vue")
  const main = read("src/main.ts")

  assert.match(bubble, /保存为指标/)
  assert.match(bubble, /metricDraftDrawerVisible/)
  assert.match(bubble, /metricDraftDatasetMissing/)
  assert.match(bubble, /指标草稿/)
  assert.match(bubble, /\/api\/metrics\/from-query\/draft/)
  assert.match(bubble, /\/api\/metrics\/from-query/)
  assert.match(bubble, /selected_metric_column/)
  assert.match(bubble, /source_dataset_id/)
  assert.match(bubble, /绑定数据集/)
  assert.match(bubble, /当前数据源下没有可绑定的同源数据集/)
  assert.match(bubble, /创建基础数据集/)
  assert.match(bubble, /openDatasetBuilderForMetric/)
  assert.match(bubble, /DatasetCenter/)
  assert.match(bubble, /datasetBuilderVisible/)
  assert.match(bubble, /handleMetricDatasetCreated/)
  assert.match(bubble, /embedded/)
  assert.match(bubble, /auto-create/)
  assert.match(bubble, /preferred-datasource-id/)
  assert.match(bubble, /suppressGlobalError: true/)
  assert.doesNotMatch(bubble, /path: "\/data-development"/)
  assert.match(bubble, /dataset_id: metricDraftForm\.dataset_id/)
  assert.match(bubble, /source_query_history_id/)
  assert.match(bubble, /pending_review/)
  assert.match(store, /datasourceId\?: number \| null/)
  assert.match(store, /datasourceId: datasourceId/)
  assert.match(store, /datasourceId: turn\.datasource_id/)
  assert.match(datasetCenter, /embedded\?: boolean/)
  assert.match(datasetCenter, /autoCreate\?: boolean/)
  assert.match(datasetCenter, /preferredDatasourceId\?: number \| null/)
  assert.match(datasetCenter, /dataset-drawer--embedded/)
  assert.match(datasetCenter, /dataset-drawer-modal--embedded/)
  assert.match(datasetCenter, /embedded-designer-shell/)
  assert.match(datasetCenter, /grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(datasetCenter, /overflow-x: hidden/)
  assert.match(datasetCenter, /defineEmits/)
  assert.match(datasetCenter, /emit\("saved"/)
  assert.match(datasetCenter, /route\.query\.create === "dataset"/)
  assert.match(datasetCenter, /openCreate\(routeDatasourceId\.value\)/)
  assert.match(datasetCenter, /delete nextQuery\.create/)
  assert.match(main, /suppressGlobalError/)
  assert.match(main, /if \(suppressGlobalError\) return Promise\.reject\(error\)/)
})

test("natural-language dashboard chart creation uses agentic mode", () => {
  const dashboard = read("src/views/DashboardCenter.vue")

  assert.match(dashboard, /canUseAgenticMode/)
  assert.match(dashboard, /探索模式仅部门管理员及以上可用/)
  assert.match(dashboard, /mode: "agentic"/)
  assert.doesNotMatch(dashboard, /mode: "explore"/)
  assert.doesNotMatch(dashboard, /mode: "text2sql"/)
})
